name: Curl Test
on:
  push:
    branches: [main]
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@latest
        with:
          version: '1.6'
      - name: Pre-Ipopt Curl Call 
        run: julia curl.jl
      - name: Concurrent Ipopt Curl Call
        run: julia curl-ipopt.jl
      - name: Post-Ipopt Curl Call
        run: julia curl.jl
