name: Test
on:
  push:
    branches: [master]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@latest
        with:
          version: '1.6'
      - run: julia -e "run(`curl -sI --proto =http,https,ftp,ftps https://jump.dev/JuMP.jl/v0.21.8/ --max-time 10 -o /dev/null --write-out '%{http_code} %{url_effective} %{redirect_url}'`)"
